### ISSUE TITLE
ESP8266-12

### ISSUE THREAD

**Issue by fatihyasar** [iboboc/smartbutton#4]
@iboboc first of all thanks for sharing your idea and schematics. 
I have worked on similar things. ESP8266-12 has unexpected behaviours. 
Some times;
- it's not boot
- it's close itself during boot.
  But, sometimes it's working as expected. 

Have you tried your schematic on ESP8266-12 ?  

I'm using your schematics without any change as well as breadboard power source. 
Do you have any idea to check something ?

**Comment by iboboc** [comment]
Hi,
Actually my project was done with ESP-12E as you can see in the pictures. https://www.hackster.io/iboboc/smartbutton-pro-06ce5d

I am wondering if there is something woring with you're wirings/soldering. I did not experienced any issues with it. Just flashed with NodeMCU latest integer firmware and with the above code.

**Comment by fatihyasar** [comment]
@iboboc thanks for quick response. It seems the problem was in my NodeMCU firmware. After re-flashed up2date firmware. It's started to working.
