### ISSUE TITLE
A Question about sample picture and schematic

### ISSUE THREAD

**Issue by fatihyasar** [iboboc/smartbutton#5]
@iboboc Hi Again, 
I have got confused between your one of sample pictures and schema. 
I'm using ESP8266-12 with latest build of NodeMCU int build.

In one of your sample pictures 
![real](https://cloud.githubusercontent.com/assets/8568703/13401842/700436d2-df16-11e5-9e37-ef329b072a67.png)

According to picture, you wire up RST,GPIO02 AND VCC together. If the device get power up, all of this pins goes to HIGH right ? 

But in your schematic 
![schematic-2](https://cloud.githubusercontent.com/assets/8568703/13401951/d7cee1f4-df16-11e5-8d2f-c264d7805fc0.jpg)
GPIO02 gets power after user press the button. 

Is there any way to explain on your sample image that in this post.

That would be great if you explain which cable goes to ? or through x resistor ? on sample picture of course.  

Best

**Comment by iboboc** [comment]
Hi, sorry for delayed reply.
You are kind of right...I need to re-open my button and check again...I might be solder it wrong first time (when I did the pictures) and then fix it without re-taking pictures again.

Basically you should follow the schematics (ignore my photos) for your button.
Make a protoptype on breadboard before, to double check your setup.

Regards,
Bobby

**Comment by fatihyasar** [comment]
@iboboc thanks for your response. I have already done with it with different approach.
